### ISSUE TITLE
Bootstrap bugged

### ISSUE THREAD

**Issue by Chincoya** [Chincoya/members-only#4]
Not every bootstrap class is applying it's styles to elements.

**Comment by ChristianOtieno** [comment]
Hi, there could be a tutorial of the same [here](https://www.digitalocean.com/community/tutorials/how-to-add-bootstrap-to-a-ruby-on-rails-application). Check it out, it might help.

**Comment by Chincoya** [comment]
SOlved by using 'Bootstrap' gem instead of 'bootstrap-rails'
